### ISSUE TITLE
Pre-Training To Remove Bias and PII

### ISSUE THREAD

**Issue by huu4ontocord** [sonoisa/t5-japanese#1]
Hi, Thank you for this work. Would it be possible to get the training code published in this repo. I'd like to experiment with pre-training with bias and PII addressed in the dataset. Any help appreciated!

**Comment by sonoisa** [comment]
Hi @ontocord,

Sorry, I have no plans to release the pre-training code at this time. This is because it is not easy to rewrite it so that it is executable for everyone.
Fortunately, the program to run the pre-training is almost identical to the one published in the following website. Please refer to the program on this site.

- https://www.ogis-ri.co.jp/otc/hiroba/technical/similar-document-search/part7.html

If you have any questions, please ask.
